### ISSUE TITLE
Disable Window Shake on OS X?

### ISSUE THREAD

**Issue by mwegner** [JetBrains/Unity3dRider#8]
Is there a command line argument available (or Rider preference setting) to disable the window shake that happens when opening a file in Rider via Unity?

**Comment by van800** [comment]
do you mean behavior as described here https://youtrack.jetbrains.com/issue/RIDER-2604

**Comment by mwegner** [comment]
That behavior doesn't bother me as much (mostly because I have Rider on its own monitor).  But maybe the shake is actually some kind of multi-monitor bug and not an intended feature?

Here's a short video (0:39) of what I'm talking about: https://www.youtube.com/watch?v=52qTxqZJZ9o

**Comment by van800** [comment]
I have tried it at one monitor with both windows (not full screen) - it also shows some "shake" and small move of the window. It is not related primary to Unity or Unity plugin or even ReSharper backend. It seems that it is IDEA frontend and it is by design ( It might get fixed when Rider will become multi-solutioned.
If it bothers you much - please make a new issue in the https://youtrack.jetbrains.com/issues/Rider
